name: Pipeline Registration

on:
  push:
    branches:
      - "main"
  workflow_dispatch:

jobs:
  register-pipeline:
    name: Register Pipeline
    runs-on: ubuntu-20.04
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_PAT }}
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Setup miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-activate-base: false
          activate-environment: rca-data-env
          channel-priority: strict
          environment-file: .ci/environment.yaml
          use-only-tar-bz2: true
      - name: Print conda env
        run: |
          conda info
          conda list
      - name: Install package
        run: pip install -e .

      - name: Run login and registration
        run: |
          # Make prefect dir
          mkdir ~/.prefect
          
          # Login
          ###prefect auth login --key ${{ secrets.PREFECT_TOKEN }}
        
          # Set backend of prefect to server
          prefect backend server
          echo "[server]" >> ~/.prefect/backend.toml
          echo "endpoint = '${{secrets.AWS_PREFECT_SERVER}}'" >> ~/.prefect/backend.toml
 
          echo "[server]" >> ~/.prefect/config.toml
          echo "[server_ui]" >> ~/.prefect/config.toml
          echo "endpoint = '${{secrets.AWS_PREFECT_SERVER}}'" >> ~/.prefect/config.toml

          # Run flow
          qaqc_pipeline --register --cloud --s3-sync
