name: Pipeline Registration

on:
  push:
    branches:
      - "main"
  workflow_dispatch:

env:
  PYTHON_VERSION: 3.8

jobs:
  register-pipeline:
    name: Register Pipeline
    runs-on: ubuntu-20.04
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_PAT }}
      - name: Setup python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Setup miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          auto-activate-base: false
          use-only-tar-bz2: true
      - name: Print conda env
        run: |
          conda info
          conda list
      - name: Install package
        run: pip install -e .

      - name: Run login and registration
        run: |
          # Make prefect dir
          mkdir ~/.prefect

          # Login
          prefect auth login --key ${{ secrets.PREFECT_TOKEN }}

          # Run flow
          qaqc_pipeline --register --cloud --s3-sync
