name: Trigger data-vent Image Rebuild

on:
  push:
    branches:
      - main

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch to data-vent
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GH_PAT }}" \
            https://api.github.com/repos/ooi-data/data-vent/dispatches \
            -d '{"event_type":"rca-data-tools-updated"}'
